kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang
  commands:
    - pwd && ls
    - go env -w GOPROXY=https://proxy.golang.com.cn,direct
    - go get -u github.com/aliyun/alibaba-cloud-sdk-go/services/alidns
    - go mod init alidns && go mod tidy
    - go build alidns.go
    - go test
